# bone_mapping.py

#TODO Gelenkpunkte Koordinaten und Rotation

bone_name_mapping = {
    "mixamorig:Hips": "hip",
    "mixamorig:Spine": "spine_01",
    "mixamorig:Spine1": "spine_02",
    "mixamorig:Spine2": "spine_03",
    "mixamorig:Neck": "neck",
    "mixamorig:Head": "head",
    "mixamorig:HeadTop_End": "head_end",

    "mixamorig:RightShoulder": "shoulder_r",
    "mixamorig:RightArm": "upperarm_r",
    "mixamorig:RightForeArm": "lowerarm_r",
    "mixamorig:RightHand": "hand_r",
    "mixamorig:LeftShoulder": "shoulder_l",
    "mixamorig:LeftArm": "upperarm_l",
    "mixamorig:LeftForeArm": "lowerarm_l",
    "mixamorig:LeftHand": "hand_l",

    "mixamorig:RightHandThumb1": "thumb_01_r",
    "mixamorig:RightHandThumb2": "thumb_02_r",
    "mixamorig:RightHandThumb3": "thumb_03_r",
    "mixamorig:RightHandThumb4": "thumb_end_r",

    "mixamorig:RightHandIndex1": "index_01_r",
    "mixamorig:RightHandIndex2": "index_02_r",
    "mixamorig:RightHandIndex3": "index_03_r",
    "mixamorig:RightHandIndex4": "index_end_r",

    "mixamorig:RightHandMiddle1": "middle_01_r",
    "mixamorig:RightHandMiddle2": "middle_02_r",
    "mixamorig:RightHandMiddle3": "middle_03_r",
    "mixamorig:RightHandMiddle4": "middle_end_r",

    "mixamorig:RightHandRing1": "ring_01_r",
    "mixamorig:RightHandRing2": "ring_02_r",
    "mixamorig:RightHandRing3": "ring_03_r",
    "mixamorig:RightHandRing4": "ring_end_r",

    "mixamorig:RightHandPinky1": "pinky_01_r",
    "mixamorig:RightHandPinky2": "pinky_02_r",
    "mixamorig:RightHandPinky3": "pinky_03_r",
    "mixamorig:RightHandPinky4": "pinky_end_r",

    "mixamorig:LeftHandThumb1": "thumb_01_l",
    "mixamorig:LeftHandThumb2": "thumb_02_l",
    "mixamorig:LeftHandThumb3": "thumb_03_l",
    "mixamorig:LeftHandThumb4": "thumb_end_l",

    "mixamorig:LeftHandIndex1": "index_01_l",
    "mixamorig:LeftHandIndex2": "index_02_l",
    "mixamorig:LeftHandIndex3": "index_03_l",
    "mixamorig:LeftHandIndex4": "index_end_l",

    "mixamorig:LeftHandMiddle1": "middle_01_l",
    "mixamorig:LeftHandMiddle2": "middle_02_l",
    "mixamorig:LeftHandMiddle3": "middle_03_l",
    "mixamorig:LeftHandMiddle4": "middle_end_l",

    "mixamorig:LeftHandRing1": "ring_01_l",
    "mixamorig:LeftHandRing2": "ring_02_l",
    "mixamorig:LeftHandRing3": "ring_03_l",
    "mixamorig:LeftHandRing4": "ring_end_l",

    "mixamorig:LeftHandPinky1": "pinky_01_l",
    "mixamorig:LeftHandPinky2": "pinky_02_l",
    "mixamorig:LeftHandPinky3": "pinky_03_l",
    "mixamorig:LeftHandPinky4": "pinky_end_l",

    # Legs
    "mixamorig:RightUpLeg": "upperleg_r",
    "mixamorig:RightLeg": "lowerleg_r",
    "mixamorig:RightFoot": "foot_r",
    "mixamorig:RightToeBase": "ball_r",
    "mixamorig:RightToe_End": "foot_end_r",

    "mixamorig:LeftUpLeg": "upperleg_l",
    "mixamorig:LeftLeg": "lowerleg_l",
    "mixamorig:LeftFoot": "foot_l",
    "mixamorig:LeftToeBase": "ball_l",
    "mixamorig:LeftToe_End": "foot_end_l"
}


BONE_LOOKUPS = {
    "mixamorig": {
        "hip": "mixamorig:Hips",
        "spine 1": "mixamorig:Spine",
        "spine 2": "mixamorig:Spine1",
        "spine 3": "mixamorig:Spine2",
        "neck": "mixamorig:Neck",
        "head": "mixamorig:Head",
        "head top": "mixamorig:HeadTop_End",
        "right shoulder": "mixamorig:RightShoulder",
        "right upper arm": "mixamorig:RightArm",
        "right forearm": "mixamorig:RightForeArm",
        "right hand": "mixamorig:RightHand",
        "left shoulder": "mixamorig:LeftShoulder",
        "left upper arm": "mixamorig:LeftArm",
        "left forearm": "mixamorig:LeftForeArm",
        "left hand": "mixamorig:LeftHand",
        "right thumb 1": "mixamorig:RightHandThumb1",
        "right thumb 2": "mixamorig:RightHandThumb2",
        "right thumb 3": "mixamorig:RightHandThumb3",
        "right thumb 4": "mixamorig:RightHandThumb4",
        "right index 1": "mixamorig:RightHandIndex1",
        "right index 2": "mixamorig:RightHandIndex2",
        "right index 3": "mixamorig:RightHandIndex3",
        "right index 4": "mixamorig:RightHandIndex4",
        "right middle 1": "mixamorig:RightHandMiddle1",
        "right middle 2": "mixamorig:RightHandMiddle2",
        "right middle 3": "mixamorig:RightHandMiddle3",
        "right middle 4": "mixamorig:RightHandMiddle4",
        "right ring 1": "mixamorig:RightHandRing1",
        "right ring 2": "mixamorig:RightHandRing2",
        "right ring 3": "mixamorig:RightHandRing3",
        "right ring 4": "mixamorig:RightHandRing4",
        "right pinky 1": "mixamorig:RightHandPinky1",
        "right pinky 2": "mixamorig:RightHandPinky2",
        "right pinky 3": "mixamorig:RightHandPinky3",
        "right pinky 4": "mixamorig:RightHandPinky4",
        "left thumb 1": "mixamorig:LeftHandThumb1",
        "left thumb 2": "mixamorig:LeftHandThumb2",
        "left thumb 3": "mixamorig:LeftHandThumb3",
        "left thumb 4": "mixamorig:LeftHandThumb4",
        "left index 1": "mixamorig:LeftHandIndex1",
        "left index 2": "mixamorig:LeftHandIndex2",
        "left index 3": "mixamorig:LeftHandIndex3",
        "left index 4": "mixamorig:LeftHandIndex4",
        "left middle 1": "mixamorig:LeftHandMiddle1",
        "left middle 2": "mixamorig:LeftHandMiddle2",
        "left middle 3": "mixamorig:LeftHandMiddle3",
        "left middle 4": "mixamorig:LeftHandMiddle4",
        "left ring 1": "mixamorig:LeftHandRing1",
        "left ring 2": "mixamorig:LeftHandRing2",
        "left ring 3": "mixamorig:LeftHandRing3",
        "left ring 4": "mixamorig:LeftHandRing4",
        "left pinky 1": "mixamorig:LeftHandPinky1",
        "left pinky 2": "mixamorig:LeftHandPinky2",
        "left pinky 3": "mixamorig:LeftHandPinky3",
        "left pinky 4": "mixamorig:LeftHandPinky4",
        "right upper leg": "mixamorig:RightUpLeg",
        "right leg": "mixamorig:RightLeg",
        "right foot": "mixamorig:RightFoot",
        "right ball": "mixamorig:RightToeBase",
        "right toe end": "mixamorig:RightToe_End",
        "left upper leg": "mixamorig:LeftUpLeg",
        "left leg": "mixamorig:LeftLeg",
        "left foot": "mixamorig:LeftFoot",
        "left ball": "mixamorig:LeftToeBase",
        "left toe end": "mixamorig:LeftToe_End",
    },
    "rp": {
        "hip": "hip",
        "spine 1": "spine_01",
        "spine 2": "spine_02",
        "spine 3": "spine_03",
        "neck": "neck",
        "head": "head",
        "head top": "head_end",
        "right shoulder": "shoulder_r",
        "right upper arm": "upperarm_r",
        "right forearm": "lowerarm_r",
        "right hand": "hand_r",
        "left shoulder": "shoulder_l",
        "left upper arm": "upperarm_l",
        "left forearm": "lowerarm_l",
        "left hand": "hand_l",
        "right thumb 1": "thumb_01_r",
        "right thumb 2": "thumb_02_r",
        "right thumb 3": "thumb_03_r",
        "right thumb 4": "thumb_end_r",
        "right index 1": "index_01_r",
        "right index 2": "index_02_r",
        "right index 3": "index_03_r",
        "right index 4": "index_end_r",
        "right middle 1": "middle_01_r",
        "right middle 2": "middle_02_r",
        "right middle 3": "middle_03_r",
        "right middle 4": "middle_end_r",
        "right ring 1": "ring_01_r",
        "right ring 2": "ring_02_r",
        "right ring 3": "ring_03_r",
        "right ring 4": "ring_end_r",
        "right pinky 1": "pinky_01_r",
        "right pinky 2": "pinky_02_r",
        "right pinky 3": "pinky_03_r",
        "right pinky 4": "pinky_end_r",
        "left thumb 1": "thumb_01_l",
        "left thumb 2": "thumb_02_l",
        "left thumb 3": "thumb_03_l",
        "left thumb 4": "thumb_end_l",
        "left index 1": "index_01_l",
        "left index 2": "index_02_l",
        "left index 3": "index_03_l",
        "left index 4": "index_end_l",
        "left middle 1": "middle_01_l",
        "left middle 2": "middle_02_l",
        "left middle 3": "middle_03_l",
        "left middle 4": "middle_end_l",
        "left ring 1": "ring_01_l",
        "left ring 2": "ring_02_l",
        "left ring 3": "ring_03_l",
        "left ring 4": "ring_end_l",
        "left pinky 1": "pinky_01_l",
        "left pinky 2": "pinky_02_l",
        "left pinky 3": "pinky_03_l",
        "left pinky 4": "pinky_end_l",
        "right upper leg": "upperleg_r",
        "right leg": "lowerleg_r",
        "right foot": "foot_r",
        "right ball": "ball_r",
        "right toe end": "foot_end_r",
        "left upper leg": "upperleg_l",
        "left leg": "lowerleg_l",
        "left foot": "foot_l",
        "left ball": "ball_l",
        "left toe end": "foot_end_l",
    },
    "smpl": {
            "hip": ":Hips",
            "spine 1": ":Spine",
            "spine 2": ":Spine1",
            "spine 3": ":Spine2",
            "neck": ":Neck",
            "head": ":Head",
            "head top": ":HeadTop_End",
            "right shoulder": ":RightShoulder",
            "right upper arm": ":RightArm",
            "right forearm": ":RightForeArm",
            "right hand": ":RightHand",
            "left shoulder": ":LeftShoulder",
            "left upper arm": ":LeftArm",
            "left forearm": ":LeftForeArm",
            "left hand": ":LeftHand",
            "right thumb 1": ":RightHandThumb1",
            "right thumb 2": ":RightHandThumb2",
            "right thumb 3": ":RightHandThumb3",
            "right thumb 4": ":RightHandThumb4",
            "right index 1": ":RightHandIndex1",
            "right index 2": ":RightHandIndex2",
            "right index 3": ":RightHandIndex3",
            "right index 4": ":RightHandIndex4",
            "right middle 1": ":RightHandMiddle1",
            "right middle 2": ":RightHandMiddle2",
            "right middle 3": ":RightHandMiddle3",
            "right middle 4": ":RightHandMiddle4",
            "right ring 1": ":RightHandRing1",
            "right ring 2": ":RightHandRing2",
            "right ring 3": "mixamorig:RightHandRing3",
            "right ring 4": ":RightHandRing4",
            "right pinky 1": "mixamorig:RightHandPinky1",
            "right pinky 2": "mixamorig:RightHandPinky2",
            "right pinky 3": "mixamorig:RightHandPinky3",
            "right pinky 4": "mixamorig:RightHandPinky4",
            "left thumb 1": "mixamorig:LeftHandThumb1",
            "left thumb 2": "mixamorig:LeftHandThumb2",
            "left thumb 3": "mixamorig:LeftHandThumb3",
            "left thumb 4": "mixamorig:LeftHandThumb4",
            "left index 1": "mixamorig:LeftHandIndex1",
            "left index 2": "mixamorig:LeftHandIndex2",
            "left index 3": "mixamorig:LeftHandIndex3",
            "left index 4": "mixamorig:LeftHandIndex4",
            "left middle 1": "mixamorig:LeftHandMiddle1",
            "left middle 2": "mixamorig:LeftHandMiddle2",
            "left middle 3": "mixamorig:LeftHandMiddle3",
            "left middle 4": "mixamorig:LeftHandMiddle4",
            "left ring 1": "mixamorig:LeftHandRing1",
            "left ring 2": "mixamorig:LeftHandRing2",
            "left ring 3": "mixamorig:LeftHandRing3",
            "left ring 4": "mixamorig:LeftHandRing4",
            "left pinky 1": "mixamorig:LeftHandPinky1",
            "left pinky 2": "mixamorig:LeftHandPinky2",
            "left pinky 3": "mixamorig:LeftHandPinky3",
            "left pinky 4": "mixamorig:LeftHandPinky4",
            "right upper leg": "mixamorig:RightUpLeg",
            "right leg": "mixamorig:RightLeg",
            "right foot": "mixamorig:RightFoot",
            "right ball": "mixamorig:RightToeBase",
            "right toe end": "mixamorig:RightToe_End",
            "left upper leg": "mixamorig:LeftUpLeg",
            "left leg": "mixamorig:LeftLeg",
            "left foot": "mixamorig:LeftFoot",
            "left ball": "mixamorig:LeftToeBase",
            "left toe end": "mixamorig:LeftToe_End",
        }
}
